unitro: unitro::data::Matrix Class Reference
unitro::data::Matrix Class Reference
#include <matrix.hpp>
Public Member Functions
Matrix (int x, int y, int z)
virtual ~Matrix ()
boost::numeric::ublas::vector
< int > GetSize ()
std::vector< std::vector< Cell > > & operator[] (int i)
Matrix & operator= (std::vector< std::vector< std::vector< Cell >>> &a)
unitro::data::Cell & operator() (boost::numeric::ublas::vector< int > v)
boost::numeric::ublas::vector
< int > GetNearCells (int i, int j, int k)
Private Member Functions
int CountCellsByAxialDirection (int axis, int i, int j, int k)
Private Attributes
std::vector< std::vector
< std::vector
< unitro::data::Cell > > > matrix_
Constructor & Destructor Documentation
unitro::data::Matrix::Matrix (int x, int y, int z) inline
virtual unitro::data::Matrix::~Matrix () inline virtual
Member Function Documentation
int unitro::data::Matrix::CountCellsByAxialDirection (int axis, int i, int j, int k) inline private
Referenced by GetNearCells().
boost::numeric::ublas::vector<int> unitro::data::Matrix::GetNearCells (int i, int j, int k) inline
Referenced by unitro::LocalMatrixView::Draw().
boost::numeric::ublas::vector<int> unitro::data::Matrix::GetSize () inline
Referenced by unitro::LocalMatrixView::Draw().
unitro::data::Cell& unitro::data::Matrix::operator() (boost::numeric::ublas::vector< int > v) inline
Matrix& unitro::data::Matrix::operator= (std::vector< std::vector< std::vector< Cell >>> & a) inline
std::vector<std::vector<Cell> >& unitro::data::Matrix::operator[] (int i) inline
Member Data Documentation
std::vector< std::vector<std::vector<unitro::data::Cell> > > unitro::data::Matrix::matrix_ private
Referenced by CountCellsByAxialDirection(), GetSize(), operator()(), and operator[]().
The documentation for this class was generated from the following file:
src/data/matrix.hpp