unitro: unitro::entity::Player Class Reference
unitro::entity::Player Class Reference
#include <player.hpp>
Public Member Functions
Player ()
virtual ~Player ()
void Draw (unitro::Resources &resources)
void Update ()
ofVec3f GetAdressInMatrix ()
Public Member Functions inherited from unitro::entity::BaseEntity
BaseEntity ()
virtual ~BaseEntity ()
Public Attributes
ofEasyCam main_cam_
Public Attributes inherited from unitro::entity::BaseEntity
unitro::entity::KineticModel kinetic_model_
Private Member Functions
double Round (double r)
Constructor & Destructor Documentation
unitro::entity::Player::Player () inline
virtual unitro::entity::Player::~Player () inline virtual
Member Function Documentation
void unitro::entity::Player::Draw (unitro::Resources & resources) inline
Referenced by unitro::LocalPlayerView::Draw(), and unitro::LocalWorldView::Draw().
ofVec3f unitro::entity::Player::GetAdressInMatrix () inline
double unitro::entity::Player::Round (double r) inline private
Referenced by GetAdressInMatrix().
void unitro::entity::Player::Update () inline
Referenced by unitro::LocalPlayerController::Update().
Member Data Documentation
ofEasyCam unitro::entity::Player::main_cam_
Referenced by unitro::LocalWorldView::Draw().
The documentation for this class was generated from the following file:
src/entity/player.hpp